### ISSUE TITLE
Build Error: Unknown type name "id"

### ISSUE THREAD

**Issue by noahemmet** [wickwirew/CRuntime#6]
When building on Linux, I'm running into the following error:
```
/app/.build/checkouts/CRuntime/Sources/CRuntime/CRuntime.h:10:7: error: unknown type name 'id'
const id _Nullable swift_allocObject(
      
/app/.build/checkouts/CRuntime/Sources/CRuntime/CRuntime.h:10:10: error: expected identifier or '('
const id _Nullable swift_allocObject(
```

Looks like it was added [here](https://github.com/wickwirew/CRuntime/commit/6cc0b1a08aeabcd603561ba45a0f9dd99f49613b#diff-a3094c9d32ab9a6d50af012f71e768d3R10), but I can't tell what the problem is. Does `id` require the objc runtime or something?

**Comment by NSExceptional** [comment]
`id` is just a typedef for `objc_object *`

I imagine this could be easily fixed by making a struct named `objc_object` and recreating the `id` typedef, but I could be wrong

**Comment by NSExceptional** [comment]
@wickwirew This can actually be fixed by just changing `id` to `void *`

**Comment by wickwirew** [comment]
just merged it, required a small fix to the Runtime project as well but it seems to be working again. Thanks!
